### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by stoyicker** [stoyicker/android-check-2#1]
- [x] CI.
- [x] Remove `report` option because it's redundant.
- [x] License.
- [x] Configurations:
  - [x] Remove 'easy' and 'hard'.
  - [x] Make the default configuration more appropriate, and let it be overwriten.
  - [x] ~~PMD: Suppress too many static imports for tests.~~
- [x] Update checker tool versions.
- [x] ~~Remove the unused import conf rule bug when the import is for javadoc.~~
- [x] When a check fails, open the report on the default browser if abortOnError == true.
- [x] Update plugin id (in README also).
- [x] Deployment.
- [x] Fix release procedure to upload to the plugin portal too.
- [x] Replace the code in the instructions with a Bintray version badge. 
- [x] Remove the deprecated of task shift and use task.doLast instead.
- [x] Find out how parent and per-tool abortOnError interact and put it in the README.
- [x] Redeploy.
- [x] Fix README and sample when the plugin is approved in jcenter and the portal.

**Comment by stoyicker** [comment]
*1: PMD does not support excluding rules per-file, so excluding TooManyStaticImports from the tests is not possible.
*2: There was no exclusion for the bugged unused import PMD rule in the conf file.
